### ISSUE TITLE
Issue with `listObjects` in v2.2.1

### ISSUE THREAD

**Issue by Retsam** [jamhall/s3rver#180]
We've got some integration tests wrapped around our S3 utility, which depend on `s3rver` and one of them started failing with the 2.2.1 release.  (Pinning the version back to 2.2.0 caused the test to start passing again)

The test adds three objects to s3, with keys `"some/dir/x"`, `"some/dir/y"`, and `"some/dir/z"`.  However, when I send this request:

```
bucket.listObjects({
    Bucket: bucketName,
    Prefix: "some/dir",
    Delimiter: '/',
    Marker: null
});
```

The result is an empty array, rather than the expected three results.  I added a `headObject` check to ensure that the data does exist before calling `listObjects`, so I think the issue must be with the `listObjects` call itself.  

Any idea why this might be suddenly breaking?  Thanks!

**Comment by specialkk** [comment]
Thanks for providing a descriptive test case.

I'm looking into right now, but it looks like the reason our tests are passing is because we have a trailing `/` on the `Prefix` field. If you check out Amazon's docs on the listObjects endpoint, they also use the delimiter at the end of the prefix.
```http
GET /?list-type=2&prefix=photos/2006/&delimiter=/ HTTP/1.1
Host: example-bucket.s3.amazonaws.com
x-amz-date: 20160501T000433Z
Authorization: authorization string
```
That said I'm pretty certain returning an empty list isn't correct behavior. I'll update in a couple hours.

**Comment by specialkk** [comment]
Okay I was actually able to verify that given your scenario, S3 **should** return an empty list. This is because if you want to treat the `/` separated segments as folders, your request is semantically equivalent to 
> Find all files that start with the name `dir` in the `/some/` directory

This is the response I got from S3:

```javascript
{ IsTruncated: false,
  Marker: '',
  Contents: [],
  Name: 'test-bucket',
  Prefix: 'some/dir',
  Delimiter: '/',
  MaxKeys: 1000,
  CommonPrefixes: [ { Prefix: 'some/dir/' } ] }
```

You can see that the prefix that shows up in `CommonPrefixes` is a "folder" that starts with the prefix given and more importantly has that trailing delimiter character so that you can just pass the value there into the next request to traverse further down the tree.

This broke in 2.2.1 because the listObjects handler was rewritten. Incidentally it looks like this case is handled more accurately now.

**Comment by Retsam** [comment]
@specialkk Thanks for looking at that.  I'll just go ahead and change that on our end.
