### ISSUE TITLE
Trying to enable cors?

### ISSUE THREAD

**Issue by zaun** [jamhall/s3rver#383]
I've got:

    new S3rver({
      port: config.s3Port,
      hostname: 'localhost',
      silent: false,
      cors: '<CORSConfiguration><CORSRule><AllowedOrigin>*</AllowedOrigin><AllowedMethod>*</AllowedMethod><MaxAgeSeconds>3000</MaxAgeSeconds><AllowedHeader>*</AllowedHeader></CORSRule></CORSConfiguration>',
      directory: path.join(__dirname, 'temp', 's3'),
      removeBucketsOnClose: true
    }).run((err, host, port) => {
      if(err) {
        return reject(err);
      }
      resolve();
    });

but I keep getting:

> Access to XMLHttpRequest at 'http://localhost:4569/media.las.com/temp/d43a4a8b-18fb-4920-986c-5801ef7fb52f?AWSAccessKeyId=key&Expires=1549339586&Signature=FLZdN5K6tWCLmSmu0VK7EdxadR8%3D&x-amz-acl=bucket-owner-full-control&x-amz-meta-mimetype=image%2Fpng&x-amz-meta-title=Test' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by kherock** [comment]
AllowedMethod can't be a wildcard, refer to the [CORS docs here](https://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html#cors-allowed-methods). I'd suggest you ensure that your config is valid on AWS before trying to use it locally, since it does report it as invalid.

![image](https://user-images.githubusercontent.com/4993980/52384690-89d79980-2a4c-11e9-97d4-30ee645a3cd7.png)
