### ISSUE TITLE
Project inactive?

### ISSUE THREAD

**Issue by fishcharlie** [jamhall/s3rver#673]
Is this project still being maintained? There haven't been any commits since July 2020, and 13 commits since the last release. There are currently 21 open issues and 29 open pull requests.

Although project maintainers don't have an obligation to continue maintaining a project, maintainers should at **LEAST** notify users that a project is no longer being maintained. This can be done by archiving a repository on GitHub, which takes less than a minute.

If this project is looking for maintainers I'd be happy to help work on maintaining it to ensure it's survival. Otherwise I respectfully ask @jamhall to at least archive the repository on GitHub so that users are aware that this project is no longer active.

**Comment by kherock** [comment]
Hi @fishcharlie - I've updated the pinned issue #623 to reflect my current availability for this project. I oversaw most contributions up until I became inactive about a year ago. I'll take responsibility for the lack of notice, so I'm sorry for not advertising the current status.

Many of the existing open PRs here are good to merge, but I simply don't have the bandwidth or motivation to ensure a cohesive major release and bugfixes thereafter.

**Comment by fishcharlie** [comment]
@kherock Thank you for the update.

Can I ask you to do one of two things?

1. Either, find someone who is able to have the bandwidth and motivation to take this project forward. I'd be happy to help do this if you are interested. I'd be happy to discuss further with you if you are interested.
2. OR archive the repo or put a notice in the README saying that the project is no longer active.

**Comment by leontastic** [comment]
@fishcharlie Why would we archive the project? That would bar people from ever making contributions again. I don't really understand this expectation that contributors need to update users on their availability to maintain projects, really the onus should be on users to determine whether the project is suitable for their needs. Sometimes maintainers come back, new maintainers show up. This project isn't so dead that it clearly should be archived.

I'd be happy to vouch for you as a collaborator if you can do some code review or if you have substantial contributions yourself. That would be great. But if that doesn't happen, I don't think it means this project should be archived. That would simply bar the next bright individual like yourself from getting current maintainers' attention and asking to join as a contributor. Especially since there doesn't seem to be a clear successor project/fork to this one. It's OK if a project becomes inactive for a while, but IMO it's too early to say this project needs to be archived. In fact there's really never a "need" to archive projects unless the project owner decides they don't want to deal with it anymore.

**Comment by leontastic** [comment]
I got hit by nostalgia seeing this issue, I made one sort of like this one just over three years ago: https://github.com/jamhall/s3rver/issues/77

@fishcharlie It would be ideal if you could provide us with specific changes you want to contribute to the project rather than giving current maintainers broad directions on how we should manage the project. Regardless, we should respect the owner's prerogative to archive what he likes.

**Comment by fishcharlie** [comment]
@leontastic 

> That would bar people from ever making contributions again.

According to [GitHub's own documentation](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/archiving-repositories): `You can also unarchive repositories that have been archived`.

Where are you getting that it would bar people from **ever** making contributions again? Seems to contradict what GitHub says, or at the very least extreme. If the project becomes active again, you can always unarchive.

---

I will point out, I said `or put a notice in the README saying that the project is no longer active`. Obviously 29 open PRs and no commits since July 2020 means the project is not active.

Shouldn't people contributing to this project at **least** be aware that no one is actively maintaining it? Why should comments like [this](https://github.com/jamhall/s3rver/pull/660#issuecomment-679122029) exist?

I completely understand that people get busy, priorities change, and people move on. Open source is all volunteer work. But part of that is a mutual respect within the community. I don't believe it's asking too much for maintainers to post a **quick** (one minute) update saying that they are no longer active. I believe that is a completely fair request of open source maintainers.

If you think that is asking too much, I'd love to hear more. But in my opinion there has to be a balance between 0 updates and no communication, and forcing maintainers to work on a project indefinitely. And posting a quick update or archiving a repo, seems to be a reasonable middle ground in my opinion.

> if you can do some code review or if you have substantial contributions yourself

That is the kind of update I'm looking for. I will see what I can do. I'm encouraged that I've had two collaborators reply to this issue pretty quickly.

I just don't want to waste my time like some of the other users who have submitted PRs. My time would be better spent elsewhere if the project was dead. So I appreciate the update.

> I got hit by nostalgia seeing this issue, I made one sort of like this one just over three years ago: #77

😄 joys of open source!!!

> It would be ideal if you could provide us with specific changes you want to contribute to the project rather than giving current maintainers broad directions on how we should manage the project

Apologizes if I didn't make it clear. The updates you just provided and you asking me to contribute is **exactly** what I was looking for here. Either the project should be willing to bring new people on, current maintainers should be active, or people should be warned that this project is no longer active. Sounds like the first option is the state of the project. I think that is a completely fair thing.

---

As for moving forward. I will try to find some free time to look through the issues, codebase, and hopefully try to review & submit some PRs. Hopefully after I get used to the codebase, and show trust in contributing, I can be considered for a maintainer role. **Really** don't want to see this project die.

**Comment by leontastic** [comment]
@fishcharlie Fair points all, you have my respect for your efforts and my apologies for not being more active lately. I've been starting to get back into open source after a long hiatus, I'd love to become active again in this project too. You motivate me!

Archiving does prevent PRs and new issues, which are useful to gather if there is no clear successor repo. If you have a more active and advanced fork it might make more sense to archive this project in that case. Until then please contribute! I'll try to get around to sorting some of the existing submissions.

**Comment by fishcharlie** [comment]
@leontastic Sounds great on all fronts!!

I just took some time to reviewing some PRs. Ideally I want to try to take a stab at implementing #492 this weekend. Slightly concerned about merge conflicts since we have so many open PRs. But we'll cross that bridge when we get to it 😆.

**Comment by jamhall** [comment]
Hi everyone! Interesting conversation! 

Let me start with saying that when I first developed s3rver a few years ago, I happened to have more free time and less responsibilities than I do now. I open-sourced the project because I thought it could be useful to the community and it’s awesome to see that it is used and appreciated.

I am very grateful to all of the contributors who have contributed to this project! 
I am particularly thankful to @leontastic and @kherock  for their fantastic contributions and support in maintaining the project! You’ve done a great job!

Alas, I no longer use s3rver in my day-to-day activities and I have other responsibilities that I need to focus on.

I apologise that I have been neglecting this project. I have been meaning to try and spend more time in maintaining this project, but alas, that hasn’t happened. Unfortunately, at the moment, due to other commitments, I am in no capacity to be an active maintainer, and I would be lying if I told you otherwise! I rely on motivated people like you, @fishcharlie, to keep the project alive. I also, personally, understand the frustration of seeing projects that I like not being maintained anymore. 

I would prefer not to archive the project as people are no longer able to create issues or open PRs. As @leontastic  has said, sometimes new maintainers come back and new maintainers show up! I would like to point out though that I have always been very open in accepting new maintainers and I really do appreciate the community's contributions to the project!

**Comment by kherock** [comment]
Seeing this whole response actually has actually motivated to help breathe some life back into this library. It does have its own special place in my heart so it is really nice to see that it hasn't been forgotten. I'll at least pick off some low langing fruit around here (I see you're already ahead of me there with all of those renovate bot updates @leontastic 😄, appreciate it). @fishcharlie I'd be happy to see what you're able to accomplish with tagging support!

**Comment by jamhall** [comment]
Yeah, this is great to see! Thanks everyone!
